### ISSUE TITLE
settings=True doesn't work

### ISSUE THREAD

**Issue by timkpaine** [timkpaine/perspective-python#29]
may need to be a string instead of a boolean?
@texodus

**Comment by texodus** [comment]
'settings' does not update perspective-viewer like other properties do, as this should really be a boolean attribute rather than a string, and boolean attributes are not quite as well supported by web components at present.

If it were, the API would look like:

    // open settings
    element.setAttribute('settings', true);

    // check element
    var is_settings_open = element.hasAttribute('settings');

    // close settings
    element.removeAttribute('settings');

I will update this issue when/if settings supports this feature in the future.

**Comment by timkpaine** [comment]
closing for now
